### ISSUE TITLE
No repo to fork or clone

### ISSUE THREAD

**Issue by michaelsimon** [learn-co-students/oo-custom-errors-v-000#2]
This lesson/lab references that this is a codealong and to fork and clone a repo. However, there does not appear to be one attached to the lesson.

**Comment by Shmuwol** [comment]
They want us to fork/clone this lesson manually, I submitted a [pull request](https://github.com/learn-co-curriculum/oo-custom-errors/pull/8l) that clarifies this requirement.

**Comment by gj** [comment]
I believe this can be closed @pletcher

**Comment by pletcher** [comment]
Thanks!
